const sorular = {
    "After": "Sonra",
    "Agreed": "Anlaşıldı",
    "Answer": "Cevap",
    "Art": "Sanat",
    "Abandon": "Terk Etmek",
    "Ability": "Hüner",
    "About": "Hakkında",
    "Above": "Üstünde",
    "Abroad": "Yurtdışı",
    "Absence": "Yokluk",
    "Absolute": "Kesin",
    "Absolutely": "Kesinlikle",
    "Abuse": "Suistimal Etmek",
    "Accept": "Kabul Etmek",
    "Access": "Giriş",
    "Accident": "Kaza",
    "Accompany": "Eşlik Etmek",
    "Accomplish": "Sonuçlandırmak",
    "Account": "Hesap",
    "Accurate": "Doğru",
    "Accuse": "Suçlamak",
    "Achieve": "Başarmak",
    "Achievement": "Başarı",
    "Acknowledge": "Kabullenmek",
    "Acquire": "Elde Etmek",
    "Across": "Karşı karşıya",
    "Act": "Davranmak",
    "Action": "Aksiyon",
    "Active": "Etkin",
    "Activity": "Aktivite",
    "Actual": "Gerçek",
    "Actually": "Aslında",
    "Adapt": "Adapte Olmak",
    "Add": "Eklemek",
    "Addition": "İlave",
    "Adequate": "Yeterli",
    "Adjust": "Ayarlamak",
    "Adjustment": "Ayarlama",
    "Administration": "İdare",
    "Administrator": "İdareci",
    "Admire": "Hayran Olmak",
    "Admiration": "Hayranlık",
    "Admission": "Kabul",
    "Admit": "Kabul Etmek",
    "Adolescent": "Ergen",
    "Adopt": "Benimsemek",
    "Adult": "Yetişkin",
    "Advance": "İlerlemek",
    "Advanced": "İleri",
    "Advantage": "Avantaj",
    "Adventure": "Macera",
    "Advertising": "Reklam",
    "Advice": "Tavsiye",
    "Advise": "Nasihat Etmek",
    "Adviser": "Müşavir",
    "Advocate": "Müdafaa Etmek",
    "Affect": "Etkilemek",
    "Afford": "Parası Yetmek",
    "Afraid": "Korkmuş",
    "Afternoon": "Öğleden Sonra",
    "Again": "Tekrar",
    "Against": "Karşı",
    "Age": "Yaş",
    "Agency": "Ajans",
    "Agenda": "Ajanda",
    "Agent": "Ajan",
    "Aggressive": "Agresif",
    "Ago": "Önce",
    "Agree": "Aynı Fikirde Olmak",
    "Agreement": "Anlaşma",
    "Agriculture": "Tarım",
    "Ahead": "İleride",
    "Aid": "Yardım Etmek",
    "Aim": "Amaçlamak",
    "Aircraft": "Uçak",
    "Airline": "Havayolu",
    "Airport": "Havalimanı",
    "Alcohol": "Alkol",
    "Alive": "Canlı",
    "All": "Hepsi",
    "Alliance": "İttifak",
    "Allow": "İzin Vermek",
    "Ally": "Müttefik",
    "Almost": "Neredeyse",
    "Alone": "Yalnız",
    "Along": "Boyunca",
    "Already": "Halihazırda",
    "Also": "Ayrıca",
    "Alternative": "Alternatif",
    "Although": "Rağmen",
    "Always": "Her Zaman",
    "Amazing": "Şaşırtıcı",
    "Among": "Arasında",
    "Amount": "Meblağ",
    "Analysis": "Analiz",
    "Analyze": "Analiz Etmek",
    "Ancient": "Antik",
    "And": "Ve",
    "Anger": "Öfke",
    "Angle": "Açı",
    "Angry": "Kızgın",
    "Animal": "Hayvan",
    "Anniversary": "Yıldönümü",
    "Announce": "Anons Etmek",
    "Annual": "Senelik",
    "Another": "Öbür",
    "Anticipate": "Ummak",
    "Anxiety": "Endişe",
    "Anybody": "Kimse",
    "Anymore": "Artık",
    "Anyone": "Hiç Kimse",
    "Anyway": "	Neyse",
    "Anywhere": "Her Yer",
    "Apart": "Ayrı",
    "Apartment": "Daire",
    "Apparent": "Görünür",
    "Apparently": "Anlaşılan",
    "Appeal": "Başvurmak",
    "Appear": "Görünmek",
    "Appearance": "Görünüş",
    "Apple": "Elma",
    "Application": "Başvuru",
    "Apply": "Başvurmak",
    "Appoint": "Atamak",
    "Appointment": "Randevu",
    "Appreciate": "Değerini Artırmak",
    "Approach": "Yanaşmak",
    "Appropriate": "Münasip",
    "Approval": "Tasvip",
    "Approve": "Onaylamak",
    "Approximately": "Takriben",
    "Architect": "Mimar",
    "Area": "Alan",
    "Argue": "Tartışmak",
    "Argument": "Argüman",
    "Arm": "Kol",
    "Armed": "Ateşli",
    "Army": "Ordu",
    "Around": "Sularında",
    "Arrange": "Ayarlamak",
    "Arrangement": "Düzenleme",
    "Arrest": "Tutuklamak",
    "Arrival": "Varış",
    "Arrive": "Ulaşmak",
    "Article": "Makale",
    "Aside": "Bertaraf",
    "Ask": "Sormak",
    "Asleep": "Uyuyan",
    "Aspect": "Hal",
    "Assault": "Saldırmak",
    "Assert": "İleri Sürmek",
    "Assess": "Değer Biçmek",
    "Assessment": "Değerlendirme",
    "Asset": "Varlık",
    "Assign": "Atamak",
    "Assignment": "Atama",
    "Assist": "Yardım Etmek",
    "Assistance": "Yardım",
    "Assistant": "Asistan",
    "Associate": "Birleştirmek",
    "Association": "Birlik",
    "Assume": "Farzetmek",
    "Assumption": "Farzetme",
    "Assure": "Garanti Etmek",
    "Atmosphere": "Atmosfer",
    "Attach": "Eklemek",
    "Attack": "Saldırmak",
    "Attempt": "Girişimde Bulunmak",
    "Attend": "Katılmak",
    "Attention": "Özen",
    "Attitude": "Tavır",
    "Attorney": "Avukat",
    "Attract": "Cezbetmek",
    "Attractive": "Çekici",
    "Attribute": "Bağlamak",
    "Audience": "Kitle",
    "Author": "Yazar",
    "Authority": "Otorite",
    "Available": "Müsait",
    "Average": "Ortalama",
    "Avoid": "Kaçınmak",
    "Award": "Ödül",
    "Aware": "Farkında",
    "Awareness": "Farkındalık",
    "Away": "Uzak",
    "Awful": "Berbat",
    "Baby": "Bebek",
    "Back": "Arka",
    "Backpack": "Sırt Çantası",
    "Bad": "Kötü",
    "Badly": "Kötü Bir Şekilde",
    "Bag": "Çanta",
    "Bake": "Pişirmek",
    "Balance": "Denge",
    "Bald": "Kel",
    "Ball": "Top",
    "Band": "Müzik Grubu",
    "Bank": "Banka",
    "Barely": "Zar Zor",
    "Basic": "Esas",
    "Basically": "Temelde",
    "Basket": "Sepet",
    "Bathroom": "Banyo",
    "Battery": "Pil",
    "Battle": "Savaş",
    "Beach": "Kumsal",
    "Bean": "Fasulye",
    "Bear": "Ayı",
    "Beautiful": "Güzel",
    "Beauty": "Güzellik",
    "Because": "Çünkü",
    "Become": "Olmak",
    "Bed": "Yatak",
    "Bedroom": "Yatak Odası",
    "Beer": "Bira",
    "Before": "Önce",
    "Begin": "Başlamak",
    "Beginning": "Başlangıç",
    "Behavior": "Davranış",
    "Behind": "Arkada",
    "Belief": "İnanç",
    "Believe": "İnanmak",
    "Belong": "Ait Olmak",
    "Below": "Aşağısında",
    "Belt": "Kemer",
    "Benefit": "Fayda",
    "Best": "En İyi",
    "Bet": "İddaa",
    "Better": "Daha İyi",
    "Between": "Arasında",
    "Big": "Büyük",
    "Bill": "Fatura",
    "Bird": "Kuş",
    "Birth": "Doğum",
    "Birthday": "Doğum Günü",
    "Bite": "Isırmak",
    "Blame": "Ayıplamak",
    "Blanket": "Battaniye",
    "Blind": "Kör",
    "Blood": "Kan",
    "Blue": "Mavi",
    "Body": "Vücut",
    "Book": "Kitap",
    "Border": "Sınır",
    "Borrow": "Ödünç Almak",
    "Boss": "Patron",
    "Bottle": "Şişe",
    "Bowl": "Kase",
    "Box": "Kutu",
    "Boyfriend": "Erkek Arkadaş",
    "Brain": "Beyin",
    "Brand": "Marka",
    "Bread": "Ekmek",
    "Break": "Kırmak",
    "Breakfast": "Kahvaltı",
    "Breast": "Göğüs",
    "Breathe": "Nefes Almak",
    "Bridge": "Köprü",
    "Bright": "Parlak",
    "Broken": "Bozuk",
    "Brother": "Erkek Kardeş",
    "Brown": "Kahverengi",
    "Brush": "Fırça",
    "Budget": "Bütçe",
    "Build": "İnşa Etmek",
    "Building": "Bina",
    "Bullet": "Mermi",
    "Burn": "Yakmak",
    "Bus": "Otobüs",
    "Business": "Iş",
    "Busy": "Meşgul",
    "Button": "Düğme",
    "Buy": "Satın Almak",
    "Buyer": "Alıcı",
    "Cabbage": "Lahana",
    "Cage": "Kafes",
    "Call off": "İptal etmek",
    "Captive": "Esir",
    "Captor": "Esir alan",
    "Carpet": "Halı",
    "Car": "Araba",
    "Cat": "Kedi",
    "Castle": "Kale",
    "Cave": "Mağara",
    "Census": "Nüfus Sayımı",
    "Charm": "Alımlı",
    "Chair": "Sandalye",
    "Chin": "Çene",
    "Child": "Çocuk",
    "Clash": "Anlaşmazlık",
    "Clay": "Kil",
    "Clerk": "Yazıcı",
    "Cliff": "Uçurum",
    "Cling": "Yapışmak",
    "Cloud": "Bulut",
    "Cloudy": "Bulutlu",
    "Clue": "İpucu",
    "Cold": "Nezle",
    "Collide": "Çarpışmak",
    "Combat": "Dövüş",
    "Comment": "Yorum",
    "Commitment": "Vaat",
    "Compatible": "Uygun",
    "Compliant": "İtaatkar",
    "Conflict": "Çatışma",
    "Cool": "Serin",
    "Cow": "İnek",
    "Count": "Saymak",
    "Crow": "Karga",
    "Create": "Yaratmak",
    "Creative": "Yaratıcı",
    "Creation": "Yaratık",
    "Cute": "Sevimli",
    "Daring": "Cesur",
    "Dawn": "Şafak",
    "Deaf": "Sağır",
    "Dear": "Sevgili",
    "Decay": "Çürümek",
    "Decline": "Reddetmek",
    "Defect": "Defo",
    "Deletion": "Silmek",
    "Delightful": "Hoş",
    "Delusion": "Aldatma",
    "Demolition": "Yıkma",
    "Dent": "Çöküntü",
    "Dependable": "Güvenilir",
    "Deportation": "Sürgün",
    "Deprive": "Yoksun Bırakmak",
    "Desperately": "Umutsuzca",
    "Destiny": "Kader",
    "Dilemma": "İkilem",
    "Dinner": "Akşam Yemeği",
    "Disgrace": "Utanç",
    "Disrupt": "Bozmak",
    "Divorce": "Boşanma",
    "Dizziness": "Baş Dönmesi",
    "Doctor": "Doktor",
    "Dog": "Köpek",
    "Drawing": "Çizim",
    "Dream": "Hayal",
    "Edit": "Düzenlemek",
    "Economy": "Ekonomi",
    "Enormous": "Muazzam",
    "Ear": "Kulak",
    "Earth": "Toprak",
    "Earing": "Küpe",
    "Earn": "Para Kazanmak	",
    "Except": "Haricinde",
    "Expect": "Ümit etmek",
    "Exile": "Sürgün",
    "Exit": "Çıkış",
    "Eastern": "Doğuya ait",
    "Effective": "Etkili",
    "Efficient": "Verimli",
    "Emergency": "Acil",
    "Elephant": "Fil",
    "Emotion": "Duygu",
    "Entertain": "Eğlendirmek",
    "Equal": "Eşit",
    "Essay": "Rapor",
    "Eye": "Göz",
    "Eyelash": "Kirpik",
    "Favorable": "Olumlu",
    "Fish": "Balık",
    "Fire": "Ateş",
    "Frosh": "Kurba",
    "Fall": "Düşmek",
    "Feasible": "Mümkün",
    "Fabric": "Kumaş",
    "Fugitive": "Kaçak",
    "Facilitate": "Kolaylaştırmak",
    "Fade": "Rengi Solmak",
    "Fun": "Eğlence",
    "Fur": "Kürk",
    "Fulfill": "Tatmin etmek",
    "Fence": "Çit",
    "Fertile": "Bereketli",
    "Fever": "Ateş",
    "Faint": "Bayılmak",
    "Flu": "Grip",
    "Fierce": "Şiddetli",
    "Finger": "Parmak",
    "Flimsy": "Dayanıksız",
    "Flee": "Kaçmak",
    "Flavor": "Tat",
    "Flat": "Daire",
    "Flaw": "Kusur",
    "Flawless": "Kusursuz",
    "Fortunate": "Minnettar",
    "Gain": "Kazanmak",
    "Gap": "Boşluk",
    "Generous": "Cömert",
    "Genius": "Deha",
    "Genuine": "Hakiki",
    "Get": "Elde Etmek",
    "Guest": "Misafir",
    "Guard": "Korumak",
    "Grow": "Büyümek",
    "Groom": "Damat",
    "Grocery Store": "Market",
    "Gravity": "Yer çekimi",
    "Grateful": "Minnettar",
    "Grass": "Çimen",
    "Glove": "Eldiven",
    "Glory": "Görkem",
    "Globe": "Küre",
    "Glow": "Parıltı",
    "Glad": "Memnun",
    "God": "Tanrı",
    "Good": "İyi",
    "Give": "Vermek",
    "Gift": "Armağan",
    "Ghost": "Hayalet",
    "Hair": "Saç",
    "Honey": "Bal",
    "Honor": "Onur",
    "Half": "Yarım",
    "High": "Yüksek",
    "Hammer": "Çekiç",
    "Hand": "El",
    "Handy": "Kullanışlı",
    "Handsome": "Yakışıklı",
    "Hang": "Asmak",
    "Happy": "Mutlu",
    "Harbor": "Liman",
    "Hat": "Şapka",
    "Hate": "Nefret",
    "Hear": "Duymak",
    "Head": "Baş",
    "Headache": "Baş ağrısı",
    "Heat": "Isı",
    "Hello": "Merhaba",
    "Help": "Yardım Etmek",
    "Herb": "Bitki",
    "Here": "Burada",
    "Howl": "Uluma",
    "Hawk": "Şahin",
    "Health": "Sağlık",
    "Hit": "Vurmak",
    "Hill": "Tepe",
    "Have": "Sahip Olmak",
    "Information": "Bilgi",
    "Inform": "Bilgilendirmek",
    "Injured": "Yaralı",
    "Image": "Görüntü",
    "Impossible": "İmkansız",
    "Insane": "Deli",
    "Incorrect": "Yanlış",
    "Invade": "İstila Etmek",
    "Introduction": "Giriş",
    "Iron": "Demir",
    "Invent": "İcat Etmek",
    "Invisible": "Görünmez",
    "Inhale": "Nefes Almak",
    "Inheritance": "Miras",
    "Innovation": "Yenilik",
    "Inquisitive": "Meraklı",
    "Insect": "Böcek",
    "Impulse": "Dürtü",
    "Inception": "Başlangıç",
    "Invade": "İstila etmek",
    "Invention": "İcat",
    "Invasion": "Akın, Saldırı",
    "Invincible": "Yenilmez",
    "Involved": "Karmaşık",
    "Ironic": "Alaylı",
    "Intelligent": "Zeki",
    "Jacket": "Ceket",
    "Jacuzzi": "Jakuzi",
    "Jam": "Reçel",
    "Jar": "Kavanoz",
    "Jeans": "Kot",
    "Jeep": "Jip",
    "Jet": "Jet",
    "Jet engine": "Jet Motoru",
    "Jewelry": "Takı",
    "Jogging": "Koşmak",
    "Jukebox": "Müzik Kutusu",
    "Junk": "Ivır Zıvır",
    "Keep": "Korumak",
    "Key": "Anahtar",
    "Kick": "Tekme",
    "Kid": "Çocuk",
    "Kill": "Öldürmek",
    "Kind": "İyi",
    "King": "Kral",
    "Kingdom": "Krallik",
    "Kiss": "Öpmek",
    "Kitchen": "Mutfak",
    "Knee": "Di̇z",
    "Knife": "Bıçak",
    "Knock": "Vurmak",
    "Knot": "Düğüm",
    "Know": "Bi̇lmek",
    "Knowledge": "Bi̇lgi̇",
    "Kidnap": "Zorla Kaçırmak",
    "Kidney": "Böbrek",
    "Kin": "Ai̇le",
    "Knight": "Si̇lahşör",
    "Knob": "Tokmak",
    "Labor": "İş Gücü",
    "Lack": "Eksi̇kli̇k",
    "Ladder": "Merdi̇ven",
    "Lady": "Hanımefendi̇",
    "Lake": "Göl",
    "Lamb": "Kuzu",
    "Lame": "Topal",
    "Lamp": "Lamba",
    "Land": "Kara",
    "Land": "İni̇ş Yapmak",
    "Language": "Di̇l",
    "Large": "Geni̇ş",
    "Last": "Son",
    "Last": "Devam Etmek",
    "Late": "Geç",
    "Laugh": "Gülmek",
    "Laundry": "Çamaşırhane",
    "Law": "Yasa",
    "Lawyer": "Avukat",
    "Lay": "Yatmak",
    "Lazy": "Tembel",
    "Legal": "Yasal",
    "Lead": "Önderli̇k Etmek",
    "Leader": "Önder",
    "Leadership": "Önderli̇k",
    "Leaf": "Yaprak",
    "Lean": "Yaslanmak",
    "Learn": "Öğrenmek",
    "Least": "En Az",
    "Leather": "Deri̇",
    "Leave": "Terk Etmek",
    "Left": "Sol",
    "Leg": "Bacak",
    "Legacy": "Mi̇ras",
    "Lemon": "Li̇mon",
    "Lend": "Ödünç Vermek",
    "Lens": "Lens",
    "Less": "Daha Az",
    "Lesson": "Ders",
    "Let": "Bırakmak",
    "Letter": "Mektup",
    "Letter Box": "Mektup Kutusu",
    "Level": "Sevi̇ye",
    "Liberal": "Li̇beral",
    "Liberty": "Serbest Olmak",
    "Library": "Ki̇taplık",
    "License": "Li̇sans",
    "Lie": "Yalan",
    "Lie": "Yatmak",
    "Life": "Yaşam",
    "Lift": "Asansör",
    "Light": "Işık",
    "Like": "Hoşlanmak",
    "Likely": "Büyük Olasılıkla",
    "Line": "Çi̇zgi̇",
    "Link": "Bi̇rleşti̇rmek",
    "Lip": "Dudak",
    "Liquid": "Sıvı",
    "List": "Li̇ste",
    "Listen": "Di̇nlemek",
    "Little": "Küçük",
    "Live": "Canli",
    "Live": "Yaşamak",
    "Life": "Hayat",
    "Living": "Yaşam Bi̇çi̇mi̇",
    "Load": "Yüklemek ",
    "Local": "Bölgesel",
    "Lock": "Ki̇li̇tlemek",
    "Long": "Uzun",
    "Look": "Bakmak",
    "Loose": "Bol",
    "Lose": "Kaybetmek",
    "Loss": "Kayıp",
    "Lot": "Mülk",
    "Loud": "Yüksek Sesli̇",
    "Love": "Sevgi",
    "Lovely": "Sevi̇mli̇",
    "Low": "Alçak",
    "Lower": "Aşağıya İndi̇rmek",
    "Luck": "Şans",
    "Lucky": "Şanslı",
    "Luggage": "Vali̇z",
    "Lunch": "Öğle Yemeği̇",
    "Lung": "Akci̇ğer",
    "Luxury": "Lüks",
    "Label": "Eti̇ket",
    "Laboratory": "Laboratory",
    "Ladle": "Kepçe",
    "Lamppost": "Sokak Lambasi",
    "Lampshade": "Abajur",
    "Lane": "Dar Yol",
    "Lash": "Kamçı",
    "Launch": "Bi̇r Şeye Başlamak",
    "Laundry-basket": "Çamaşır Sepeti̇",
    "League": "Li̇g",
    "Leak": "Akıntı",
    "Lease": "Beli̇rli̇ Bi̇r Zaman İçi̇n Ki̇ralama",
    "Lecture": "Konferans Vermek",
    "Length": "Uzunluk",
    "Lettuce": "Salata",
    "Lever": "Kaldıraç",
    "Liar": "Yalancı",
    "Lick": "Yalamak",
    "Lid": "Kapak",
    "Lighter": "Çakmak",
    "Limit": "Hat",
    "Liquidate": "Tasfi̇ye Etmek",
    "Literature": "Edebi̇yat",
    "Litter": "Çöp",
    "Liver": "Karaci̇ğer",
    "Loaf": "Bütün Ekmek",
    "Loan": "Ödünç Vermek",
    "Lobster": "Istakoz",
    "Locate": "Kurmak",
    "Lonely": "Yalnız",
    "Lorry": "Kamyon",
    "Loyal": "Sadık",
    "Loyalty": "Sadakat",
    "Memorial": "Bi̇r Ki̇şi̇ni̇n Anısına Yapılan Yapıt",
    "Memorize": "Ezberlemek",
    "Memory": "Hafiza",
    "Men": "Adamlar",
    "Mend": "Tami̇r Etmek",
    "Mental": "Zi̇hi̇nsel",
    "Mention": "Bahsetmek",
    "Merchant": "Tüccar",
    "Mercy": "Merhamet",
    "Mere": "Sadece",
    "Merry": "Mutlu",
    "Mess": "Kargaşa",
    "Message": "Mesaj",
    "Meter": "Ölçek",
    "Method": "Metot",
    "Meter": "Metre",
    "Mice": "Fareler",
    "Middle": "Orta",
    "Midnight": "Gece Yarısı",
    "Military": "Askeri̇",
    "Milk": "Süt",
    "Mill": "Deği̇rmen",
    "Mimic": "Takli̇t Etmek",
    "Mind": "Akıl",
    "Mind": "Bi̇ri̇ne Bakmak",
    "Mine": "Beni̇m",
    "Minimum": "En az",
    "Minister": "Bakan",
    "Minor": "Önemsi̇z",
    "Minority": "Azınlık",
    "Minus": "Eksi̇",
    "Minute": "Daki̇ka",
    "Mirror": "Ayna",
    "Miss": "Özlemek",
    "Miss": "Kadın",
    "Missile": "Füze",
    "Mission": "Mi̇syon",
    "Mistake": "Hata",
    "Misunderstand": "Yanlış Anlamak",
    "Mix": "Karıştırmak",
    "Model": "Model",
    "Moderate": "Ilımlı",
    "Modern": "Modern",
    "Modest": "Alçakgönüllü",
    "Moment": "An",
    "Monday": "Pazartesi̇",
    "Money": "Para",
    "Monkey": "Maymun",
    "Month": "Ay",
    "Moon": "Ay",
    "More": "Daha Fazla",
    "Morning": "Sabah",
    "Mosque": "Cami̇",
    "Most": "En Çok",
    "Mother": "Anne",
    "Motor": "Motor",
    "Mountain": "Dağ",
    "Mouse": "Fare",
    "Mouth": "Ağız",
    "Move": "Hareket Etmek",
    "Movement": "Hareket",
    "Much": "Çok ",
    "Mud": "Çamur",
    "Murder": "Ci̇nayet",
    "Music": "Müzi̇k",
    "Must": "Zorunluluk",
    "My": "Beni̇m",
    "Mystery": "Bi̇li̇nmezli̇k",
    "Machine": "Maki̇ne",
    "Machine-gun": "Maki̇neli̇ Tüfek",
    "Mad": "Deli̇",
    "Madam": "Bayan",
    "Magic": "Büyü",
    "Mail": "Posta",
    "Main": "Ana",
    "Make": "Yapmak",
    "Make -up": "Makyaj",
    "Male": "Erkek",
    "Man": "Adam",
    "Manage": "Yönetmek",
    "Management": "Yöneti̇m",
    "Manager": "Yöneti̇ci̇",
    "Manner": "Tavır",
    "Many": "Bi̇rçok",
    "Map": "Hari̇ta",
    "March": "Marş",
    "Mark": "İşaretlemek",
    "Market": "Pazar",
    "Marry": "Evlenmek",
    "Marvelous": "Şahane",
    "Mask": "Maske",
    "Mass": "Ki̇tle",
    "Master": "Uzman",
    "Match": "Uyuşmak",
    "Material": "Malzeme",
    "Matter": "Mesele",
    "May": "Mayıs",
    "Me": "Bana",
    "Meal": "Yemek",
    "Mean": "Anlamına Gelmek",
    "Mean": "Ortalama",
    "Meaning": "Anlam",
    "Means": "Sti̇l",
    "Meantime": "Bu Arada",
    "Meanwhile": "Aynı Anda",
    "Measure": "Ölçü",
    "Meat": "Et",
    "Mechanic": "Mekani̇k",
    "Medal": "Madalya",
    "Medicine": "İlaç",
    "Meet": "Buluşmak",
    "Meeting": "Toplantı",
    "Melody": "Ezgi̇",
    "Melon": "Kavun",
    "Melt": "Eri̇mek",
    "Member": "Üye",
    "Memorable": "Unutulmayacak",
    "Memorandum": "Memorandum",
    "Magazine": "Magazi̇n",
    "Magnet": "Mıknatıs",
    "Magnificent": "İhti̇şam",
    "Magnifying-glass": "Büyüteç",
    "Maid": "Kadın Hi̇zmetçi̇",
    "Maintain": "Bakım Onarım",
    "Major": "Büyük, Önemli̇",
    "Majority": "Çoğunluk",
    "Maniac": "Manyak",
    "Manual": "El İle Yapılan",
    "Manufacture": "Üretmek",
    "Margin": "Marj",
    "Marmalade": "Marmelat",
    "Massacre": "Katli̇am",
    "Massive": "Çok Büyük",
    "Mat": "Hasır",
    "Mate": "Arkadaş",
    "Mathematics": "Matemati̇k",
    "Mattress": "Yatak",
    "Mature": "Olgun",
    "Maturity": "Olgunluk ",
    "Maximum": "Maksi̇mum",
    "Meadow": "Çayır",
    "Mechanic": "Maki̇ni̇st",
    "Medical": "Tıbbi",
    "Merely": "Sadece",
    "Merge": "Bi̇rleşerek Kaybolma",
    "Merit": "Hak Etmek",
    "Might": "Kuvvet",
    "Microphone": "Mi̇krofon",
    "Mild": "Hafi̇f",
    "Millet": "Dari",
    "Millionaire": "Mi̇lyoner",
    "Mince": "Kıyma ",
    "Miracle": "Muci̇ze",
    "Miser": "Hasi̇s",
    "Miserable": "Sefi̇l",
    "Misery": "Sefalet",
    "Mislay": "Nereye Koyduğunu Unutmak",
    "Mobile": "Oynak",
    "Moisture": "Nem",
    "Mole": "Köstebek",
    "Monument": "Anıt",
    "Mood": "Mi̇zaç",
    "Moral": "Ahlak",
    "Morale": "Moral",
    "Mortgage": "İpotek",
    "Mosquito": "Si̇vri̇si̇nek",
    "Moss": "Yosun",
    "Motion": "Hareket",
    "Motive": "Moti̇vlenmek",
    "Mud-guard": "Çamurluk",
    "Multiply": "Çarpmak",
    "Murmur": "Mırıldanmak",
    "Muscle": "Pazu",
    "Museum": "Müze",
    "Mushroom": "Mantar",
    "Muslim": "Müslüman",
    "Mustard": "Hardal",
    "Mute": "Sesi̇z",
    "Mutter": "Mırıldanmak",
    "Mutual": "Müşterek",
    "Nail": "Tırnak/ Çivi",
    "Name": "İsim",
    "Narrow": "Dar",
    "Nation": "Ulus",
    "National": "Ulusal",
    "Native": "Yerli",
    "Natural": "Doğal",
    "Nature": "Doğa",
    "Near": "Yakın",
    "Necessary": "Gerekli",
    "Necessity": "Gereklik",
    "Neck": "Boyun, Ense",
    "Necklace": "Kolye",
    "Need": "Gereksinim, İhtiyaç",
    "Needle": "İğne, Şiş",
    "Neglect": "İhmal Etmek",
    "Neighbour": "Komşu",
    "Neither": "Hiçbiri",
    "Neither…Nor…": "Ne O..Ne Öbürü",
    "Nephew": "Yeğen (Erkek)",
    "Nerve": "Sinir",
    "Nervous": "Gergin",
    "Nest": "Yuva, Kuş Yuvası",
    "Net": "Ağ",
    "Never": "Hiçbir Zaman, Asla",
    "Nevertheless": "Buna Rağmen, Hala, Ama",
    "New": "Yeni",
    "News": "Haber",
    "Newspaper": "Gazete",
    "Next": "En Yakın, Bir Sonraki, Ertesi",
    "Nice": "Hoş",
    "Niece": "Yeğen (Kız)",
    "Night": "Gece",
    "No": "Hayır",
    "Noble": "Soylu",
    "Nobody": "Hiç Kimse",
    "Noise": "Gürültü",
    "None": "Hiçbirişi",
    "Noon": "Öğle Zamanı",
    "Normal": "Normal",
    "North": "Kuzey",
    "Nose": "Burun",
    "Not": "Değil",
    "Nothing": "Hiçbir Şey",
    "Notice": "Duyuru/ Dikkatini Çekmek",
    "November": "Kasım",
    "Now": "Şimdi",
    "Nowadays": "Bugünlerde",
    "Nowhere": "Hiçbir Yer",
    "Nuisance": "Sıkıntı, Dert",
    "Number": "Sayı, Numaralandırmak",
    "Nurse": "Hemşire, Hasta Bakıcı",
    "Nut": "Kuruyemiş (Fındık vs.)",
    "Napkin": "Peçete",
    "Narrate": "Anlatmak, Söylemek",
    "Nasty": "Pis, Kötü Kokulu, Hoş Olmayan",
    "Naughty": "Yaramaz",
    "Negotiate": "Görüşmek, Müzakere",
    "Network": "Şebeke, Çalışma Ağı",
    "Nickname": "Takma isim, Lakap",
    "Nightmare": "Kabus",
    "Nominate": "Aday Göstermek",
    "Nonsense": "Saçmalık",
    "Novel": "Roman",
    "Nude": "Çıplak",
    "Oak": "Meşe",
    "Obey": "Söz Dinlemek, İtaat Etmek",
    "Object (v)": "İtiraz Etmek",
    "Object (n)": "Nesne, Obje/ Amaç",
    "Observation": "Gözlem",
    "Observe": "Gözlem Yapmak",
    "Obvious": "Aşikar",
    "Occupation": "Meslek, İşgal",
    "Occupy": "İşgal Etmek, Oturmak, Kaplamak",
    "Ocean": "Okyanus",
    "October": "Ekim (Ayı)",
    "Of": "İyelik Eki, -Nin",
    "Off": "Yok Olma, Eksilmek/ Kapatmak",
    "Offend": "Kızdırmak, İncitmek (Birini)",
    "Offer": "Teklif Etmek",
    "Office": "Ofis",
    "Officer": "Subay, Memur",
    "Official": "Resmi",
    "Often": "Sık Sık",
    "Oil": "Yağ/ Petrol",
    "Old": "Eski, Yaşlı",
    "On": "Üzerinde",
    "Once": "Bir Kez, Bir An Önce",
    "One": "Bir",
    "Only": "Sadece, Yalnızca",
    "Open": "Açık, Açmak",
    "Operate": "Çalışmak",
    "Operation": "Operasyon, Ameliyat",
    "Operator": "Operatör",
    "Opinion": "Düşünce",
    "Opportunity": "Fırsat",
    "Opposite": "Zıt, Ters",
    "Optimist": "İyimser",
    "Or": "Veya",
    "Orange": "Portakal/ Turuncu",
    "Order": "Emir, Sipariş, Düzen, Sıra",
    "Ordinary": "Sıradan, Normal",
    "Organ": "Org, Organ, Organizasyon, Kuruluş",
    "Organize": "Organize Etmek",
    "Origin": "Köken, Orijin",
    "Other": "Diğer",
    "Otherwise": "Başka Türlü, Yoksa, Aksi Taktirde",
    "Our": "Bizim",
    "Out": "Dışarı",
    "Out-of-date": "Modası Geçmiş, Eski",
    "Outside": "Dışarı",
    "Oven": "Fırın",
    "Over": "Üstünde/ Bitmek",
    "Overcome": "Üstesinden Gelmek",
    "Owe": "Borçlu Olmak",
    "Own": "Sahip Olmak",
    "Owner": "Sahip",
    "Ox": "Boğa",
    "Occur": "Olmak",
    "Odd": "Tuhaf, Acayip",
    "Old-fashioned": "Eski Moda",
    "Onion": "Soğan",
    "Option": "Seçme, Seçenek",
    "Oral": "Sözlü",
    "Orbit": "Yörünge",
    "Original": "Orjinal, İlk, Yeni",
    "Owl": "Baykuş",
    "Oxygen": "Oksijen",
    "Oyster": "İstiridye",
    "Pack": "Paketlemek",
    "Packet": "Paket",
    "Page": "Sayfa",
    "Pain": "Acı, Ağrı",
    "Painful": "Ağrılı",
    "Paint": "Boyamak, Boya",
    "Painter": "Ressam, Boyacı",
    "Pair": "Çift",
    "Palace": "Saray",
    "Pale": "Soluk, Solgun (Renk)",
    "Pan": "Tava",
    "Panic": "Panik",
    "Paper": "Kağıt, Gazete, Evrak, Kimlik",
    "Paradise": "Cennet",
    "Paragraph": "Paragraf",
    "Parcel": "Parça",
    "Parent": "Anne-Baba, Ebeveyn",
    "Park": "Park, Park Etmek",
    "Parliament": "Parlamento",
    "Parrot": "Papağan",
    "Part": "Kısım, Bölüm, Ayırmak",
    "Particular": "Yalnız, Özel, Titiz",
    "Partner": "Ortak, Partner",
    "Part-time": "Yarım Gün",
    "Party": "Parti",
    "Pass": "Geçmek, Geçirmek",
    "Passage": "Pasaj",
    "Passenger": "Yolcu",
    "Passport": "Pasaport",
    "Password": "Parola",
    "Past": "Geçmiş",
    "Patience": "Sabır",
    "Patient (adj.)": "Sabırlı",
    "Patient (n)": "Hasta",
    "Pathetic": "Acınası",
    "Pay": "Ödemek",
    "Payment": "Ödeme",
    "Peace": "Barış",
    "Pear": "Armut",
    "Peculiar": "Garip",
    "Pen": "Tükenmez Kalem",
    "Penalty": "Ceza",
    "Pencil": "Kurşun Kalem",
    "People": "Halk, İnsanlar",
    "Pepper": "Biber",
    "Per": "Her",
    "Perfect": "Kusursuz, Yetkin",
    "Perform": "Çalışmak, Uygulamak",
    "Performance": "Performans",
    "Perhaps": "Belki",
    "Permission": "İzin",
    "Permit": "İzin Vermek, İzin Kağıdı",
    "Person": "Kişi",
    "Personality": "Kişilik",
    "Persuade": "İkna Etmek",
    "Petrol": "Petrol",
    "Phone": "Telefon",
    "Photo": "Fotoğraf",
    "Piano": "Piyano",
    "Pick": "Seçmek",
    "Picture": "Resim",
    "Pie": "Pasta, Turta",
    "Piece": "Parça",
    "Pig": "Domuz",
    "Pigeon": "Güvercin",
    "Pile": "Üst Üste Koymak",
    "Pill": "Hap",
    "Pilot": "Pilot",
    "Pin": "Toplu İğne",
    "Pine": "Çam",
    "Pineapple": "Ananas",
    "Pink": "Pembe",
    "Pipe": "Boru/ Pipo/ Flüt",
    "Pity": "Acımak (What A Pity: Ne Yazık)",
    "Place": "Yer/ Yerleştirmek",
    "Plain": "Açık, Ortada, Düz",
    "Plan": "Plan, Planlama",
    "Plane": "Uçak",
    "Planet": "Gezegen",
    "Plant": "Bitki",
    "Plantation": "Ekili Yer",
    "Plate": "Tabak",
    "Play": "Oynamak/ Çalmak (Bir Müzik Aletini)",
    "Player": "Oyuncu, Çalan",
    "Pleasant": "Keyifli, Zevkli",
    "Please": "Lütfen",
    "Pleasure": "Zevk",
    "Plenty": "Çok Sayıda",
    "Plough": "Toprağı Sürmek",
    "Plug": "Fiş, Banyo Tıkacı",
    "Plus": "Artı",
    "Pocket": "Cep",
    "Poem": "Şiir",
    "Poet": "Şair",
    "Poetry": "Şiirler, Şairlik, Şiirle İlgili",
    "Point": "Nokta, Uç",
    "Poison": "Zehir",
    "Police": "Polis",
    "Policy": "Poliçe, Yönetim İlkesi, Politika",
    "Polish": "Parlatmak",
    "Polite": "Kibar",
    "Political": "Politik",
    "Politician": "Politikacı, Politikayla Uğraşan",
    "Politics": "Politik",
    "Pool": "Havuz",
    "Poor": "Fakir, Yoksul, Zavallı",
    "Population": "Nüfus",
    "Pork": "Domuz Eti",
    "Port": "Liman",
    "Portrait": "Portre",
    "Position": "Durum, Konum",
    "Positive": "Emin, Kesin/ Olumlu",
    "Possess": "Sahip Olmak",
    "Possession": "Sahiplik",
    "Possibility": "Olasılık",
    "Possible": "Olası, Mümkün",
    "Post": "Posta, İşaret, Devriye Gezmek (Askerde)",
    "Postpone": "Ertelemek",
    "Pot": "Tencere",
    "Potato": "Patates",
    "Pour": "Dökmek, Akıtmak",
    "Powder": "Toz, Pudra",
    "Power": "Güç",
    "Powerful": "Güçlü",
    "Practical": "Pratik",
    "Practice": "Alıştırma",
    "Practise": "Alıştırma Yapmak",
    "Praise": "Övmek",
    "Pray": "Dua Etmek",
    "Preach": "Vaaz Vermek",
    "Predict": "Tahmin Etmek",
    "Prefer": "Yeğlemek, Tercih Etmek",
    "Pregnant": "Hamile",
    "Prejudice": "Önyargı",
    "Preparation": "Hazırlık",
    "Prepare": "Hazırlamak",
    "Presence": "Varlık",
    "Present": "Burada, Mevcut, Şimdiki, Armağan",
    "Present": "Sunmak",
    "President": "Başkan",
    "Press": "Baskı, Ütüleme, Basın",
    "Press": "Baskı Yapmak, Basmak",
    "Pressure": "Basınç, Baskı",
    "Pretend": "Gibi Gözükmek, Taklit Yapmak",
    "Pretty": "Sevimli, Oldukça",
    "Prevent": "Korumak",
    "Previous": "Önceki",
    "Price": "Fiyat",
    "Pride": "Onur, Gurur",
    "Priest": "Rahip",
    "Prince": "Prens",
    "Principal": "En Önemli, Prensip, Ana Para (Borçta)",
    "Print": "Basmak (Harfler vs.), İz",
    "Prison": "Hapishane",
    "Prisoner": "Mahkum, Esir",
    "Private": "Özel",
    "Prize": "Ödül",
    "Probable": "Olası",
    "Problem": "Sorun, Problem",
    "Produce": "Üretmek",
    "Product": "Ürün",
    "Production": "Üretim",
    "Profession": "Meslek",
    "Profit": "Kar",
    "Programme": "Program",
    "Progress": "Gelişme",
    "Promise": "Söz Vermek",
    "Pronounce": "Telaffuz Etmek",
    "Proof": "Kanıt",
    "Proper": "Uygun, Doğru",
    "Property": "Mal, Mülk (Bir Kişinin Sahip Olduğu), Eşya",
    "Proposal": "Plan, Öneri",
    "Propose": "Planını Açıklamak, Evlilik Teklif Etmek",
    "Protect": "Korumak",
    "Protest": "Protesto",
    "Proud": "Gururlu",
    "Prove": "Kanıtlamak",
    "Provide": "Sağlamak, Tedarik Etmek",
    "Pub": "Pub, Birahane",
    "Public": "Halk (Public Sector: Devlet Sektörü)",
    "Publish": "Basım (Bir Yayını)",
    "Pull": "Çekmek",
    "Pullover": "Kazak/ Arabayı Durdurmak, Kenara Çekmek",
    "Pump": "Pompa",
    "Punch": "Delmek/ Yumruklamak",
    "Punish": "Cezalandırmak",
    "Pupil": "Öğrenci/ Gözbebeği",
    "Puppet": "Kukla",
    "Puppy": "Genç Köpek",
    "Purchase": "Satın Almak",
    "Purple": "Mor",
    "Purpose": "Amaç",
    "Push": "İtmek",
    "Put": "Koymak",
    "Puzzle": "Bulmaca, Problem",
    "Pyjamas": "Pijama",
    "Packed": "Kalabalık, Bir Sürü İnsan",
    "Palm": "Avuç/ Palmiye Ağacı",
    "Panel": "Panel",
    "Pants": "Don/ Pantolon",
    "Parachute": "Paraşüt",
    "Parade": "Resmi Geçit",
    "Participate": "Başkalarıyla Birlikte Çalışma, Oynama, Katılma",
    "Passive": "Pasif, Eylemsiz",
    "Pasta": "Makarna (Hamurdan Yapılan Şeyler)",
    "Paste": "Beyaz Tutkal, Macun, Hamur",
    "Pastime": "Hoş İyi Zaman",
    "Path": "Patika, Küçük Yol",
    "Patrol": "Devriye",
    "Patron": "Destekleyici Kişi, Devamlı Müşteri",
    "Pause": "Mola, Ara",
    "Paw": "Hayvan Pençesi",
    "Pea": "Bezelye",
    "Peach": "Şeftali",
    "Peak": "Zirve, Tepe",
    "Peanut": "Yer Fıstığı",
    "Pearl": "İnci",
    "Peasant": "Çiftçi, Köylü Kesim",
    "Pedal": "Pedal",
    "Pedestrian": "Yaya Giden",
    "Peel": "Kabuk Soymak (Meyve)",
    "Penknife": "Çakı",
    "Pension": "Emekli Maaşı",
    "Perfume": "Parfüm",
    "Peril": "Büyük Tehlike",
    "Period": "Çağ, Devir/ Adet (Hali)",
    "Permanent": "Devamlı, Sürekli",
    "Persist": "Devam Etmek",
    "Pessimist": "Kötümser",
    "Petrol Station": "Benzinci",
    "Philosophy": "Fizolofi",
    "Physical": "Fiziksel",
    "Picket": "Grev Gözcüsü, Fabrika Önünde Bekleme",
    "Pickle": "Turşu",
    "Pillow": "Yastık",
    "Pillowcase": "Yastık Kılıfı",
    "Pincers": "Kerpeten, Kıskaç (Yengeç vs.)",
    "Pinch": "Çimdiklemek, Sıkıştırmak (Kapıya Vb.)",
    "Pioneer": "Öncü",
    "Pistol": "Tabanca",
    "Pity": "Acımak (What A Pity : Ne Yazık)",
    "Plastic": "Plastik",
    "Platform": "Platform/ Yüksekçe Yer, Kürsü/ Peron",
    "Playground": "Oyun Sahası",
    "Plum": "Erik/ Bonbon şekeri",
    "Plumber": "Musluk Tamircisi",
    "Pole": "Kutup, Direk, Kazık",
    "Porcelain": "Porselen",
    "Porter": "Hamal, Kapıcı",
    "Postage": "Posta Ücreti",
    "Poverty": "Fakirlik",
    "Precious": "Kıymetli, Çok Sevilen",
    "Precisely": "Kesinlikle, Tam Manasıyla",
    "Prescription": "Reçete",
    "Preserve": "Korumak, Konserve Yapmak",
    "Primarily": "Ana Olarak",
    "Primary": "Önceleri, Eskiden/ Ana, İlk Okul",
    "Primitive": "İlkel/ Basit/ Modası Geçmiş",
    "Priority": "Öncelik",
    "Privilege": "İmtiyaz",
    "Process": "İşlem",
    "Prohibit": "Yasaklamak",
    "Promote": "İlerleme, Terfi Etme, Tanıtım (Ürün vs.Satış İçin)",
    "Promotion": "Terfi",
    "Propeller": "İleriye Yürüten Şey, Vapur, Uçak Pervanesi",
    "Proportion": "Orantı",
    "Prosecute": "Kavuşturmak, Dava Açmak, Suçlamak",
    "Proverb": "Atasözü",
    "Provocation": "Kışkırtma",
    "Provoke": "Kışkırtmak, Kızdırmaya Neden Olmak",
    "Publicity": "İlan, Reklam, Yayımlama",
    "Pull Up": "Aracı Durdurmak",
    "Pulse": "Nabız, Vuruş",
    "Pumpkin": "Kabak",
    "Punctual": "Tam Zamanında",
    "Pure": "Saf, Temiz",
    "Purse": "Küçük El Çantası",
    "Pyramid": "Piramit",
    "Quality": "Nitelik, Kalite",
    "Quantity": "Miktar",
    "Quarrel": "Tartışmak, Atışmak",
    "Quarter": "Çeyrek",
    "Queen": "Kraliçe",
    "Question": "Soru/ Sormak",
    "Queue": "Sıra, Kuyruk",
    "Quick": "Çabuk",
    "Quiet": "Sessiz, Sakin, Huzurlu",
    "Quite": "Hemen Hemen, Yaklaşık Olarak",
    "Quiz": "Küçük Test",
    "Qualified": "Ehliyetli, Kalifiye",
    "Quota": "Kota, Kontenjan",
    "Quote": "Aktarma, Söyleme",
    "Rabbit": "Tavşan",
    "Race": "Irk, Yarış, Yarışmak",
    "Radiator": "Radyatör",
    "Radio": "Radyo",
    "Rail": "Ray",
    "Railway": "Tren Yolu",
    "Rain": "Yağmur",
    "Raincoat": "Yağmurluk",
    "Raise": "Yükseltmek, Zam Yapmak, Yetiştirmek",
    "Range": "Aralık, Alan",
    "Rank": "Sıra, Rütbe, Sosyal Sınıf",
    "Rapid": "Çabuk, Hızlı",
    "Rare": "Nadir",
    "Rate": "Hız, Oran",
    "Rather": "Epey, Çok Değil",
    "Raw": "Ham, Çiğ",
    "Razor": "Ustura, Traş Makinesi",
    "Reach": "Erişmek",
    "Read": "Okumak",
    "Ready": "Hazır",
    "Realize": "Fark Etmek",
    "Really": "Gerçekten",
    "Reason": "Neden, Akıl",
    "Reasonable": "Makul",
    "Recall": "Anımsamak",
    "Receipt": "Makbuz",
    "Receive": "Almak, Karşılamak",
    "Recent": "Yakın Zamanda Olan",
    "Reception": "Resmi Davet, Resepsiyon",
    "Recognize": "Tanımak",
    "Recommend": "Tavsiye Etmek",
    "Record": "Kayıt, Plak, Rekor",
    "Recover": "İyileşmek, (Kaybedilen Bir Şeyi) Bulmak",
    "Red": "Kırmızı, Kızıl",
    "Reduce": "Azaltmak",
    "Reflect": "Yansıtmak",
    "Refugee": "Tehlikeden Kaçan, Kazazede",
    "Refuse": "Reddetmek",
    "Regard": "Dikkat, Düşünce, Bakmak, İnanmak",
    "Regret": "Üzgün Olmak, Pişman Olmak",
    "Regular": "Düzenli, Olağan",
    "Reject": "Kabul Etmemek",
    "Relation": "İlişki, Akrabalık",
    "Relationship": "İlişki, İletişim",
    "Relative": "Akraba, Göreceli",
    "Relax": "Rahatlamak, Gevşemek",
    "Release": "Serbest Bırakmak, Gevşetmek",
    "Relief": "Rahatlama",
    "Relieve": "Uzaklaştırmak",
    "Religion": "Din",
    "Remain": "Geriye Kalmak, Yerinde Durmak",
    "Remark": "Belirtmek, Açıklama",
    "Remarkable": "Dikkate Değer",
    "Remember": "Unutmamak, Anımsamak",
    "Remind": "Anımsatmak",
    "Remote": "Uzak",
    "Remove": "Uzaklaştırmak",
    "Rent": "Kiralamak",
    "Repair": "Onarmak",
    "Repay": "Geri Ödemek",
    "Repeat": "Tekrarlamak",
    "Replace": "Yeniden Yerleştirmek",
    "Replacement": "Yerleştirme",
    "Reply": "Yanıtlamak, Yanıt",
    "Report": "Rapor, Rapor Etmek",
    "Represent": "Temsil Etmek",
    "Representative": "Temsilci",
    "Republic": "Cumhuriyet",
    "Request": "Rica Etmek, Rica",
    "Require": "Gereksinmek",
    "Rescue": "Kurtarmak",
    "Reserve": "Rezerv, Rezervasyon Yaptırmak",
    "Resign": "İstifa Etmek",
    "Resist": "Karşı Koymak",
    "Respect": "Saygı Duymak",
    "Respectable": "Saygıdeğer",
    "Responsible": "Sorumlu",
    "Rest": "Dinlenmek, Geriye Kalan",
    "Restaurant": "Restoran, Lokanta",
    "Result": "Sonuç",
    "Retire": "Emekli Olmak",
    "Return": "Geri Dönmek",
    "Revenge": "Öç Almak, İntikam",
    "Reward": "Ödül",
    "Rib": "Kaburga",
    "Ribbon": "Kurdele, Şerit",
    "Rice": "Pirinç",
    "Rich": "Zengin",
    "Ride": "Ata Binmek, Bisiklete Binmek",
    "Ridiculous": "Gülünç, Saçma",
    "Right": "Hak, Doğru, Haklı, Sağ Taraf",
    "Ring": "Yüzük, Halka, Çalmak (Zil Çalması), Telefon Etmek",
    "Ripe": "Olgun, Ham Değil",
    "Rise": "Yükselmek",
    "Risk": "Risk",
    "Risky": "Riskli",
    "River": "Nehir",
    "Road": "Yol",
    "Roar": "Kükreme",
    "Roast": "Rosto, Fırında Pişirmek",
    "Rob": "Soygun Yapmak",
    "Rock": "Kaya, Sallanmak",
    "Role": "Rol",
    "Roll": "Yuvarlanmak",
    "Roof": "Çatı",
    "Room": "Oda",
    "Root": "Kök",
    "Rope": "Halat, İp",
    "Rose": "Gül, Pembe",
    "Rough": "Kaba",
    "Round": "Yuvarlak",
    "Row": "Sıra, Gürültü, Kürek Çekmek",
    "Royal": "Kraliyete Ait",
    "Rub": "Sürmek, Sürtmek, Ovmak",
    "Rubbish": "Çöp, Saçma",
    "Rude": "Kaba",
    "Rule": "Yönetmek, Kural",
    "Ruler": "Kural Koyucu, Yönetici, Cetvel",
    "Rumble": "Gürlemek",
    "Run": "Koşmak, Çalıştırmak (Fabrika, Şirket vs.), Kaçak, Kontrol Dışı",
    "Rush": "Çabuk Davranmak",
    "Racket": "Raket",
    "Radar": "Radar",
    "Railing": "Bahçe Parmaklıkları",
    "Ram": "Koç, Vurmak, Toslamak",
    "Rash": "Hızlı, Acele",
    "Rat": "Sıçan",
    "Rear": "Yetiştirmek (İnsan, Kuş, Bitki), Arka, Arka Taraf",
    "Recession": "Duraklama, Gerileme, Ekonomide Durgunluk",
    "Recipe": "Yemek Tarifi",
    "Recollect": "Hatırlamak",
    "Reconcile": "Uzlaşma, Anlaşma Yapmak",
    "Reconciliation": "Uzlaşma",
    "Referee": "Hakem",
    "Referendum": "Referandum, Halk Oylaması",
    "Refill": "Doldurmak",
    "Refreshments": "Sandviç, Tost, İçecek (Gar, İstasyon Gibi Yerlerde)",
    "Refrigerator": "Buzdolabı",
    "Region": "Bölge",
    "Register": "Kütük, Sicil, Kayıt, (Register Post: Taahhütlü Mektup)",
    "Regulation": "Yönetmelik, Yasa",
    "Relate": "Anlatmak, Nakletmek (Formal Tell)",
    "Relevant": "Bağıntılı, Konuyla İlişkili",
    "Reliable": "Güvenilir",
    "Reluctant": "İsteksiz",
    "Remedy": "Çare",
    "Reputation": "İtibar, Ün",
    "Research": "Araştırma",
    "Resent": "Hoşlanmamak, Kızmak",
    "Reside": "Oturmak, İkamet Etmek",
    "Resident": "Bölgede Yaşayan, Oturan",
    "Respond": "Cevap Vermek",
    "Restore": "Geri Verme, Yeniden Kullanıma Açma",
    "Restrict": "Sınırlamak",
    "Reverse": "Ters, Arka",
    "Revise": "Tekrar Gözden Geçirip Düzeltmek",
    "Revolution": "Devrim",
    "Rifle": "Tüfek",
    "Rocket": "Roket",
    "Route": "Rota",
    "Rubber": "Silgi, Lastik",
    "Rug": "Küçük Halı, Kilim",
    "Ruin": "Harabe, Yıkım Mahvetme",
    "Safe": "Güvenli",
    "Sail": "Yelken Açmak",
    "Same": "Aynı",
    "Sand": "Kum",
    "Sit": "Oturmak",
    "Save": "Kurtarmak",
    "Saw": "Testere",
    "Say": "Söylemek",
    "Scale": "Ölçek",
    "School": "Okul",
    "Science": "Bilim",
    "Scientist": "Bilim Adamı",
    "Score": "Skor",
    "Sea": "Deniz",
    "Seat": "Koltuk",
    "Second": "Saniye",
    "Section": "Bölüm",
    "See": "Görmek",
    "Seed": "Tohum",
    "Seem": "Görünmek",
    "Seen": "Görülmüş",
    "Sell": "Satmak",
    "Send": "Göndermek",
    "Sense": "His",
    "Sent": "Gönderilmiş",
    "Sentence": "Cümle",
    "Separate": "Ayrı",
    "Serve": "Hizmet Etmek",
    "Set": "Ayarlamak",
    "Settled": "Ayarlanmış",
    "Seven": "Yedi",
    "Several": "Birkaç",
    "Shade": "Gölge",
    "Shape": "Şekil",
    "Sharp": "Keskin",
    "She": "O (Kadın)",
    "Ship": "Gemi",
    "Shoes": "Ayakkabı",
    "Shop": "Dükkan",
    "Short": "Kısa",
    "Should": "Zorunda Olmak",
    "Shoulder": "Omuz",
    "Shout": "Bağırmak",
    "Show": "Göstermek",
    "Shown": "Gösterilmiş",
    "Shy": "Utangaç",
    "Side": "Yan",
    "Sight": "Görüş",
    "Sign": "İşaret",
    "Signal": "Sinyal",
    "Silent": "Sessiz",
    "Similar": "Benzer",
    "Simple": "Basit",
    "Since": "-den Beri",
    "Sing": "Şarkı Söylemek",
    "Sir": "Efendi",
    "Sister": "Kız Kardeş",
    "Sit": "Oturmak",
    "Six": "Altı",
    "Size": "Boyut",
    "Skin": "Deri",
    "Sky": "Hava",
    "Sleep": "Uyku",
    "Slowly": "Yavaşça",
    "Small": "Küçük",
    "Smell": "Koklamak",
    "Smile": "Gülümsemek",
    "Snow": "Kar",
    "Snowy": "Karlı",
    "So": "Şöyle",
    "Soft": "Yumuşak",
    "Soil": "Toprak",
    "Soldier": "Asker",
    "Solution": "Çözüm",
    "Some": "Bazı",
    "Someone": "Birisi",
    "Something": "Bir Şey",
    "Sometimes": "Bazen",
    "Son": "Erkek Çocuk",
    "Song": "Şarkı",
    "Soon": "Yakında",
    "Sound": "Ses",
    "South": "Güney",
    "Southern": "Güneyli",
    "Space": "Uzay, Boşluk",
    "Speak": "Konuşmak",
    "Special": "Özel",
    "Speed": "Hız",
    "Spell": "Hecelemek",
    "Spot": "Nokta",
    "Spread": "Yayılmak",
    "Spring": "İlkbahar",
    "Square": "Kare",
    "Stand": "Ayakta Durmak",
    "Star": "Yıldız",
    "Start": "Başlamak",
    "State": "Durum",
    "Statement": "İfade",
    "Stay": "Kalmak",
    "Steel": "Çelik",
    "Step": "Adım",
    "Stick": "Yapışmak",
    "Still": "Halen",
    "Stone": "Taş",
    "Store": "Mağaza",
    "Stove": "Ocak",
    "Stood": "Ayakta Durmuş",
    "Stop": "Durmak",
    "Store": "Dükkan",
    "Story": "Hikaye",
    "Straight": "Düz",
    "Strange": "Garip",
    "Stream": "Akıntı",
    "Street": "Sokak",
    "Stretch": "Genişletmek",
    "String": "Dizi",
    "Strong": "Güçlü",
    "Student": "Öğrenci",
    "Study": "Çalışmak",
    "Subject": "Konu",
    "Substance": "Madde",
    "Such": "Örneğin",
    "Suddenly": "Aniden",
    "Suffix": "Son Ek",
    "Sugar": "Şeker",
    "Suggested": "Tavsiye Edilmiş",
    "Sum": "Özet",
    "Summer": "Yaz",
    "Sun": "Güneş",
    "Supply": "Malzeme",
    "Suppose": "Tahmin Yürütmek",
    "Sure": "Emin",
    "Surface": "Yüzey",
    "Surprise": "Sürpriz",
    "Sweet": "Tatlı, Sevimli",
    "Swim": "Yüzmek",
    "Syllabus": "Ders Programı",
    "Symbol": "Sembol",
    "System": "Sistem",
    "Table": "Masa",
    "Tail": "Kuyruk",
    "Take (v)": "Almak",
    "Talk": "Konuşmak",
    "Tall": "Uzun",
    "Tea": "Çay",
    "Teacher": "Öğretmen",
    "Team": "Takım",
    "Tell": "Söylemek",
    "Temperature": "Sıcaklık",
    "Ten": "On",
    "Term": "Dönem",
    "Test (v)": "Denemek",
    "Their": "Onların",
    "Them": "Onlar",
    "Then": "Sonra",
    "There": "Orada",
    "These": "Bunlar",
    "They": "Onlar (İnsan)",
    "Thick": "Kalın",
    "Thin": "İnce",
    "Thing": "Şey",
    "Think": "Düşünmek",
    "Third": "Üçüncü",
    "This": "Bu",
    "Those": "Onlar",
    "Though": "-e Rağmen",
    "Thought": "Düşünce",
    "Thousands": "Binlerce",
    "Three": "Üç",
    "Through": "Arasından",
    "Thus": "Nitekim",
    "Tied": "Bağlı",
    "Time": "Zaman",
    "Tiny": "Küçücük",
    "Today": "Bugün",
    "Together": "Birlikte",
    "Tone": "Ton",
    "Took": "Almak (Geçmiş Zaman)",
    "Tool": "Alet",
    "Top": "Üst",
    "Total": "Toplam",
    "Touch": "Dokunmak",
    "Toward": "-e Doğru",
    "Town": "Yerleşke",
    "Trade": "Ticaret",
    "Train": "Tren, Eğitmek",
    "Travel": "Yolculuk",
    "Tree": "Ağaç",
    "Triangle": "Üçgen",
    "Trip": "Yolculuk",
    "Trouble": "Sorun",
    "Truck": "Kamyon",
    "True": "Doğru",
    "Try": "Denemek",
    "Tube": "Tüp",
    "Turn": "Dönüş",
    "Two": "İki",
    "Type": "Yazmak",
    "Ugly": "Çirkin",
    "Umbrella": "Şemsiye",
    "Uncle": "Dayı, Amca",
    "Unconscious": "Bilinçsizlik",
    "Under": "Altta, Alta",
    "Underclothes": "İç Çamaşırı",
    "Understand": "Anlamak",
    "Unemployment": "İşsizlik",
    "Unfair": "Adaletsiz",
    "Unhappy": "Mutsuz",
    "Unhealthy": "Sağlıksız",
    "Uniform": "Üniforma, Tek Tip",
    "Union": "Sendika, Birleşme",
    "Unite": "Birleşmek",
    "University": "Üniversite",
    "Universe": "Kainat, alem",
    "Unknown": "Bilinmeyen",
    "Unlikely": "Az İhtimalle",
    "Unlock": "Kilidi Açmak",
    "Until": "Kadar (Belli Bir Zamana Kadar)",
    "Upper": "Üst",
    "Upstairs": "Üst Kat, Yukarısı",
    "Up to date": "Bugüne Kadar",
    "Upward": "Yukarıya Doğru",
    "Urge": "Dürtme, (Israr Ederek) Yaptırma, Zorlamak",
    "Urgent": "Acil",
    "Us": "Biz",
    "Use": "Kullanım/ Fonksiyon",
    "Use (v)": "Kullanmak",
    "Useful": "Kullanışlı",
    "Undergo": "Katlanmak, Çekmek, Bir Olayın Olması",
    "Underline": "Yazının, Kelimenin Altını Çizmek",
    "Unfair": "Adil Olmayan",
    "Unit": "Birim, 1-9 Arasındaki Sayılar",
    "Up To You": "Sana Kalmış, Nasıl İstersen (It is Up To You)",
    "Upon": "Üstünde",
    "Upside-down": "Tepetaklak, Ters Dönmek",
    "Urban": "Şehirsel, Kente Ait (Urban Life: Şehirsel Yaşam)",
    "Vain": "Gereksiz, Boşuna",
    "Valley": "Vadi",
    "Valuable": "Değerli",
    "Value": "Değer",
    "Variety": "Fark, Çeşitlilik, Çeşit",
    "Various": "Değişik, Çeşitli",
    "Vegetable": "Sebze",
    "Vehicle": "Taşıt Aracı (Kamyon, Tır, Araba V.B)",
    "Very": "Çok, Tam",
    "Veto": "Veto, Veto Etmek",
    "Victim": "Kurban, Kazazede",
    "Victor": "Galip",
    "Victory": "Utku, Zafer, Yengi",
    "View": "Görünüm, Manzara",
    "Villa": "Villa",
    "Village": "Köy",
    "Vine": "Bağ",
    "Violent": "Kaba Kuvvet Kullanan, Şiddet",
    "Visa": "Vize",
    "Visible": "Görünen",
    "Vision": "Görüş, İmge",
    "Visit": "Ziyaret Etmek",
    "Visitor": "Ziyaretçi, Konuk",
    "Vocabulary": "Kelime Dağarcığı",
    "Voice": "Ses",
    "Volume": "Hacim",
    "Vote": "Oy Vermek, Oy",
    "Voyage": "Deniz Yolculuğu",
    "Vulgar": "Kaba, İlkel",
    "Vacation": "Tatil",
    "Vacuum Cleaner": "Elektrik Süpürgesi",
    "Van": "Minibüs",
    "Vanilla": "Vanilya",
    "Vase": "Vazo",
    "Vein": "Damar",
    "Velvet": "Kadife",
    "Verb": "Fiil",
    "Verdict": "Hüküm",
    "Vertical": "Dikey",
    "Vet": "Veteriner",
    "Vicious Circle": "Kısır Döngü",
    "Victim": "Kurban",
    "Victimize": "Kurban Etmek (Grubun Suçunu Bir Kişiye Yüklemek.)",
    "Vinegar": "Sirke",
    "Violin": "Keman",
    "Vital": "Çok Önemli",
    "Volcano": "Volkan, Yanardağ",
    "Volleyball": "Voleybol",
    "Voluntary": "Gönüllü",
    "Vomit": "Kusmak",
    "Vowel": "Sesli Harf (A,E,I) Gibi",
    "Vulnerable": "Zayıf, Korumasız",
    "Wait": "Beklemek",
    "Walk": "Yürümek",
    "Wall": "Duvar",
    "Want": "İstemek",
    "War": "Savaş",
    "Warm": "Sıcak",
    "Was": "Olmak (Geçmiş)",
    "Wash": "Yıkamak",
    "Watch": "Izlemek",
    "Water": "Su",
    "Wave": "Dalga",
    "Way": "Yol",
    "We": "Biz",
    "Wear": "Giymek",
    "Weather": "Hava",
    "Week": "Hafta",
    "Weight": "Kilo",
    "Well": "Iyi",
    "Went": "Gitmek (Geçmiş)",
    "Were": "Olmak (Çoğul, Geçmiş)",
    "West": "Batı",
    "Western": "Batılı",
    "What": "Ne",
    "Wheel": "Tekerlek",
    "When?": "Ne Zaman?",
    "Where": "Nerede?",
    "Whether": "Eğer",
    "Which": "Hangisi?",
    "While": "Süresince",
    "White": "Beyaz",
    "Who?": "Kim?",
    "Whole": "Bütün",
    "Whose?": "Kimin?",
    "Why?": "Neden?",
    "Wide": "Geniş",
    "Wife": "Eş (Kadın)",
    "Wild": "Vahşi",
    "Will": "Istek",
    "Win": "Kazanmak",
    "Wind": "Rüzgar",
    "Window": "Pencere",
    "Wing": "Kanat",
    "Winter": "Kış",
    "Wire": "Kablo",
    "Wish": "Dilemek",
    "With": "Birlikte",
    "Within": "İçinde",
    "Without": "Olmadan",
    "Woman": "Kadın",
    "Wonder": "Merak Etmek",
    "Wood": "Odun",
    "Word": "Kelime",
    "Work": "İş",
    "Worker": "İşçi",
    "World": "Dünya",
    "Write": "Yazmak",
    "Written": "Yazılı",
    "Wrong": "Yanlış",
    "Xenophobia": "Yabancı Düşmanlığı",
    "X-ray": "Röntgen",
    "Xmas": "Noel",
    "Xylophone": "Ksilofon",
    "Yard": "Bahçe",
    "Year": "Yıl",
    "Yellow": "Sarı",
    "Yes": "Evet",
    "Yet": "Henüz",
    "You": "Sen",
    "Young": "Genç",
    "Your": "Senin",
    "Yourself": "Kendin",
    "Zeal": "Şevk",
    "Zap": "Vurmak",
    "Zealous": "Gayretli",
    "Zebra": "Zebra",
    "Zucchini": "Kabak",
    "Zealot": "Fanatik",
    "Zazoo": "Adam",
    "Zinc": "Çinko",
    "Zip Code": "Posta Kodu",
    "Zipper": "Fermuar",
    "Zodiac": "Zodyak, burçlar",
    "Zone": "Bölge",
    "Zero": "Sıfır",
    "Zoo": "Hayvanat Bahçesi",
};
document.addEventListener('DOMContentLoaded', function() {
    // Animasyonu uygulamak istediğimiz elementi seçiyoruz.
    var animatedText = document.getElementById('animatedText');
  
    // Elemente 'fadeOut' sınıfını ekliyoruz ki animasyon başlasın.
    animatedText.classList.add('fadeOut');
  
    // Animasyonun tamamlanmasını bekliyoruz (20 saniye süre verdik).
    setTimeout(function() {
      // Animasyon tamamlandıktan sonra elementi sayfadan kaldırıyoruz.
      animatedText.style.display = 'none';
    }, 20000); // Buradaki zaman milisaniye cinsinden, yani 20 saniye.
});


const soruLabel = document.getElementById('soru');
const secimlerDiv = document.getElementById('secimler');

function secilen(secim) {
    const dogruCevap = sorular[soruLabel.textContent];
    if (secim === dogruCevap) {
        showPopup('Doğru!');
        yeniSoru();
    } else {
        showPopup('Yanlış!');
    }
}

function showPopup(message) {
    var modal = document.getElementById("myModal");
    var modalMessage = document.getElementById("modal-message");
    modalMessage.textContent = message;

    var span = document.getElementsByClassName("close")[0];
    span.onclick = function () {
        modal.style.display = "none";
    }

    modal.style.display = "block";

    setTimeout(function () {
        modal.style.display = "none";
    }, 1500); // 1,5 saniye sonra modalı kapat
}

function yeniSoru() {
    const soru = Object.keys(sorular)[Math.floor(Math.random() * Object.keys(sorular).length)];
    const dogruCevap = sorular[soru];

    soruLabel.textContent = soru;

    const secenekler = Object.values(sorular).sort(() => Math.random() - 0.5).slice(0, 4);
    secenekler[Math.floor(Math.random() * secenekler.length)] = dogruCevap;

    secimlerDiv.innerHTML = '';
    secenekler.forEach(secenek => {
        const button = document.createElement('button');
        button.textContent = secenek;
        button.addEventListener('click', () => secilen(secenek));
        secimlerDiv.appendChild(button);
    });
}

yeniSoru();